# Values for the deployment of the postgresql
postgresql:
  fullnameOverride: postgres
  image:
    tag: 11.14.0-debian-10-r17
  auth:
    username: postgres
    existingSecret: spring-boot-helm-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
  commonLabels:
    name: postgres
    component: database
    manager: helm
  databasePort: 5432

configmap:
  name: spring-boot-helm-configmap

secret:
  name: spring-boot-helm-secret

# Values for the deployment of your app
app:
  name: spring-boot-helm
  component: backend
  manager: helm
  image:
    repository: spring-boot-helm
    tag: 1.0.0

deployments:
  name: spring-boot-helm
  containerPort: 8080
  imagePullPolicy: Never
  replicas: 1

initContainers:
  name: check-db-ready
  image: postgres:16.3-alpine
  command: "['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting for database; sleep 10; done;']"

service:
    port: 8080
